name: Turners AutoMatchmaker Build & Test

on:
  push:
    branches:
      - development/Kelsie

env:
  AZURE_WEBAPP_NAME: "M3-Prediction-API"
  AZURE_WEBAPP_PACKAGE_PATH: "./"
  NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install
        run: |
          npm install

      - name: npm build
        run: |
          npm run build --if-present

      - name: test
        env:
          PREDICTION_KEY: ${{ secrets.PREDICTION_KEY }}
          PORT: ${{ secrets.PORT }}
          CONTENT_TYPE: ${{ secrets.CONTENT_TYPE }}
          API_ADDRESS: ${{ secrets.API_ADDRESS }}
        run: |
          npm run test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.M3_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        env:
          PREDICTION_KEY: ${{ secrets.PREDICTION_KEY }}
          PORT: ${{ secrets.PORT }}
          CONTENT_TYPE: ${{ secrets.CONTENT_TYPE }}
          API_ADDRESS: ${{ secrets.API_ADDRESS }}
