name: CI Test

on:
push:
branches: -feature/Kelsie

jobs:
test_push:
runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
with: node-version: 20.x
-run: npm ci
-run: npm test
-run: npm run build
